[build-system]
requires = ["setuptools >= 77.0.3"]
build-backend = "setuptools.build_meta"

[project]
name = "sm_webserver_utils"
version = "1.2.0b1"
authors = [
  { name="Steven Marshall", email="stevenmarshall@uvic.ca" },
]
description = "Utilities for working with bioinformatics webservers."
readme = "README.md"
classifiers = [
    "Programming Language :: Python :: 3",
    "Operating System :: OS Independent",
]
license = "MIT"
license-files = ["LICEN[CS]E*"]
dependencies = [
    "biopython",
    "pandas",
    "gffpandas",
]

[project.urls]
Homepage = "https://github.com/StevenMarshallUVic/webserver-utils"
Issues = "https://github.com/StevenMarshallUVic/webserver-utils/issues"
